# version: '3.8'

services:
  app:
    build:
      context: ./
      dockerfile: Dockerfile
    image: nodeapp
    environment:
      - PORT=${PORT}
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_DATABASE=${DB_DATABASE}
      - DB_HOST=${DB_HOST}
    volumes:
      - ".:/app"
      - /app/node_modules  # anonymous volume to exclude subfolder
    ports:
      - "80:${PORT}"
    depends_on:
      - db
    networks:
      - pgnodeapp
    command: sh -c './wait-for db:5432 -- npm run build-start'

  db:
    image: postgres:12-alpine
    environment:
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_DATABASE}
    volumes:
      - postgres-db:/var/lib/postgresql/data
    networks:
      pgnodeapp:
        aliases:
          - "postgres"

networks:
  pgnodeapp:
    driver: bridge

volumes:
  postgres-db:
