# version: "3.8"

services:
  api:
    build:
      context: ./
      dockerfile: ./Dockerfile
    image: flaskapp
    ports:
      - "5000:${PORT}"
    container_name: api
    environment:
      - PORT=${PORT}
      - DATABASE_URL=${DATABASE_URL}
      - FLASK_DEBUG=${FLASK_DEBUG}
    networks:
      pgflaskapp:
    volumes:
      - ".:/app"
    depends_on:
      db:
        condition: service_healthy
        restart: true
    # command: ["./wait-for", "db:5432", "--", "bash", "entrypoint.sh"]
    command: ["bash", "entrypoint.sh"]
  db:
    image: postgres:12-alpine
    environment:
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_DATABASE}
    volumes:
      - postgres-db:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${DB_USERNAME} -d ${DB_DATABASE}" ]
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 10s
    networks:
      pgflaskapp:
        aliases:
          - "postgres"

volumes:
  postgres-db:

networks:
  pgflaskapp:
    driver: bridge
